"""The typed surface of ``hyperuuid._native`` — the PyO3 extension, and equally the
``_wasm`` backend that stands in for it under the same name (``tests/test_typing.py`` holds
both to this file). ``hyperuuid`` validates and converts its arguments before calling in, so
these are the already-narrowed shapes: a timestamp here is an ``int`` or ``None``, never a
``datetime``.
"""

import datetime
import uuid

def new_v4() -> uuid.UUID: ...
def new_v5(namespace: uuid.UUID, name: str | bytes) -> uuid.UUID: ...
def new_v6(unix_millis: int | None = None) -> uuid.UUID: ...
def new_v7(unix_millis: int | None = None) -> uuid.UUID: ...
def new_v6_batch(count: int, unix_millis: int | None = None) -> list[uuid.UUID]: ...
def new_v7_batch(count: int, unix_millis: int | None = None) -> list[uuid.UUID]: ...
def fill_v6_bytes(buffer: bytearray, unix_millis: int | None = None) -> None: ...
def fill_v7_bytes(buffer: bytearray, unix_millis: int | None = None) -> None: ...
def v6_timestamp(uuid_value: uuid.UUID) -> datetime.datetime: ...
def v7_timestamp(uuid_value: uuid.UUID) -> datetime.datetime: ...
def v6_unix_millis(uuid_value: uuid.UUID) -> int: ...
def v7_unix_millis(uuid_value: uuid.UUID) -> int: ...
def v6_to_sql_order(uuid_value: uuid.UUID) -> uuid.UUID: ...
def v6_from_sql_order(uuid_value: uuid.UUID) -> uuid.UUID: ...
def v7_to_sql_order(uuid_value: uuid.UUID) -> uuid.UUID: ...
def v7_from_sql_order(uuid_value: uuid.UUID) -> uuid.UUID: ...
def native_version() -> str: ...
def _bind() -> None: ...
